default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: applewatch

test:
  <<: *default
  database: applewatch

production:
  <<: *default
  database: applewatch

